apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      nodeSelector:
        role: platform
      containers:
        - name: backstage-app
          image: backstage:0.1.1 # This gets renamed in the overlay. Overlay is updated by CI pipeline.
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7007
          envFrom:
            - secretRef:
                name: backstage-postgres-secrets
            - secretRef:
                name: backstage-secrets
            - configMapRef:
                name: backstage-config
          # # https://backstage.io/docs/plugins/observability/#health-checks
          # readinessProbe:
          #   httpGet:
          #     port: 7007
          #     path: /healthcheck
          # livenessProbe:
          #   httpGet:
          #     port: 7007
          #     path: /healthcheck
