apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backstage-configmap.yaml
  - backstage-deployment.yaml
  - backstage-ingress.yaml
  - backstage-sealedsecrets.yaml
  - backstage-service.yaml
