version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - general-network
    restart: unless-stopped

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.8.0
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - general-network
    restart: unless-stopped


  platform-service:
    build: ./apps/platform
    ports:
      - "7000:7000"
      - "9464:9464"
    environment:
      - PORT=7000
      - RENTAL_SERVICE_URL=http://rental-service:7001
      - VEHICLES_SERVICE_URL=http://vehicles-service:7002
      - SCHEDULER_INTERVAL=5000
    networks:
      - general-network
    depends_on:
      - rental-service
      - vehicles-service
    restart: unless-stopped

  rental-service:
    build: ./apps/rental
    ports:
      - "7001:7001"
      - "9465:9465"
    environment:
      - PORT=7001
    networks:
      - general-network
    restart: unless-stopped

  vehicles-service:
    build: ./apps/vehicles
    ports:
      - "7002:7002"
      - "9466:9466"
    environment:
      - PORT=7002
    networks:
      - general-network
    restart: unless-stopped


networks:
  general-network:
    name: general-network
    driver: bridge
