apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

namespace: ${{ values.team }}-dev
patches:
  - path: patch-replicas.yaml
  - path: patch-ingress.yaml
  - path: patch-config.yaml
