apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - target:
      kind: Ingress
      name: ${{ values.name }}
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: ${{ values.name }}.local
      - op: replace
        path: /spec/ingressClassName
        value: traefik-dev
