apiVersion: v1
kind: ConfigMap
metadata:
  name: ${{ values.serviceFullName }}-config
data:
  PORT: "3000"
  NODE_ENV: "dev"
  ENVIRONMENT: "dev"
  SERVICE_NAMESPACE: "${{ values.team }}-dev"
  METRICS_PREFIX: "${{ values.serviceFullName }}_"
  SERVICE_NAME: "${{ values.serviceFullName }}"
  # OTEL_EXPORTER_OTLP_ENDPOINT: "http://tempo.observability-dev.svc:4318"  # Uncomment when Tempo is deployed
