apiVersion: v1
kind: ConfigMap
metadata:
  name: ${{ values.serviceFullName }}-config
data:
  PORT: "3000"
  NODE_ENV: "dev"
  METRICS_PREFIX: "${{ values.serviceFullName }}_"
  SERVICE_NAME: "${{ values.serviceFullName }}"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://collector:4317"
