apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.serviceFullName }}
  labels:
    app: ${{ values.serviceFullName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.serviceFullName }}
  template:
    metadata:
      labels:
        app: ${{ values.serviceFullName }}
    spec:
      containers:
        - name: k8s-node-api
          image: ${{ values.serviceFullName }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: ${{ values.serviceFullName }}-config
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
