apiVersion: v1
kind: Service
metadata:
  name: ${{ values.serviceFullName }}
spec:
  selector:
    app: ${{ values.serviceFullName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
