apiVersion: v1
kind: Service
metadata:
  name: ${{ values.serviceFullName }}
  labels:
    app: ${{ values.serviceFullName }}
    team: ${{ values.team }}
spec:
  selector:
    app: ${{ values.serviceFullName }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: metrics
      protocol: TCP
      port: 3000
      targetPort: metrics
