global:
  scrape_interval: 10s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'platform-service'
    static_configs:
      - targets: ['platform-service:9464']
  - job_name: 'rental-service'
    static_configs:
      - targets: ['rental-service:9465']
  - job_name: 'vehicles-service'
    static_configs:
      - targets: ['vehicles-service:9466']