apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - backstage-sealedsecrets.yaml
  - postgres-sealedsecrets.yaml
namespace: backstage-dev
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: backstage
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: backstage.local
      - op: replace
        path: /spec/ingressClassName
        value: traefik-dev
    target:
      kind: Ingress
      name: backstage
images:
  - name: backstage
    newName: p6hi/backstage
    newTag: sha-6a7de7d6698ad9d490621d8f775fe0d716cf813d
