apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backstage.yaml
  - platform-traefik.yaml
  - sealed-secrets.yaml
  - platform-resources.yaml
  - kube-prometheus-stack.yaml
